workflows:
  sample-workflow:
    name: CICD Codemagic Pipeline
    max_build_duration: 120
    instance_type: mac_mini_m2
scripts:
  - name: Build the .app
    script: |
      # build using project
      xcodebuild build \
        -project "CICDCodeMagic.xcodeproj" \
        -scheme "CICDCodeMagic" \
        CODE_SIGN_IDENTITY="" \
        CODE_SIGNING_REQUIRED=NO \
        CODE_SIGNING_ALLOWED=NO
